config/routes.rb
InventoryManagement::Application.routes.draw do
  resources :work_orders

  resources :receiving_orders

  resources :pricing_rules

  resources :rma_orders

  resources :shipping_orders

  resources :packages

  resources :pick_orders

  resources :customers

  resources :carriers

  resources :business_processes

  resources :accounts

  resources :posticks

  resources :vendor_materials

  resources :addresses

  resources :vendors

  resources :fields_groups

  resources :documented_materials

  resources :product_groups

  resources :material_groups

  resources :employee_groups

  resources :schema_groups

  resources :application_users

  resources :user_groups

  resources :rols

  resources :activities

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :located_materials

  resources :manufacture_orders

  resources :transfer_orders

  resources :consignment_orders

  resources :purchase_orders

  resources :sales_orders

  resources :schema_fields

  resources :schema_items

  resources :schemas

  resources :groups

  resources :employees

  resources :users

  resources :documents

  resources :materials

  resources :products

  resources :locations

  resources :warehouses

  resources :companies

  root :to => 'companies#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_and_belongs_to_many :rols
end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :inventories
  has_many :addresses
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_one :defaultCarrier, :class_name => "Carrier"
  has_many :addresses
  #has_one :defaultTerm  Find out what this is
  #has_one :defaultShippingTerm  Find out what this is
  #has_one tax_rate
  #has_many accountNumbers
  #has_one default account
  #has_one default address
end

app/models/document.rb
class Document < ActiveRecord::Base
  #we need this table to keep record of the qty of product in this location
  has_many :documentedProducts
  has_many :products, :through => :documentedProducts
  
  has_many :documentedMaterials
  has_many :materials, :through => :documentedMaterials
  
  has_many :packages
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :applicationUsers
  has_and_belongs_to_many :employeeGroups
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :company
  has_and_belongs_to_many :warehouses
end

app/models/location.rb
class Location < ActiveRecord::Base
  #we need this table to keep record of the qty of product in this location
  has_many :locatedproducts, :class_name => "LocatedProduct"
  has_many :products, :through => :locatedproducts
  
  #we need this table to keep record of the qty of materials in this location
  has_many :locatedmaterials, :class_name => "LocatedMaterial"
  has_many :materials, :through => :locatedmaterials
  
  #we need this table to keep record of location hierarchy
  has_many :childlocations, :class_name => "Location"
  belongs_to :parentlocation, :foreign_key => "parentlocation_id", :class_name => "Location"
  
  belongs_to :warehouse
end

app/models/material.rb
class Material < ActiveRecord::Base
  has_many :productmaterialdetails, :class_name => "ProductMaterialDetail"
  has_many :products, :through => :productmaterialdetails
  
  #we need this table to keep record of the qty of product in a particular location
  has_many :locatedMaterials
  has_many :locations, :through => :locatedMaterials
  
  #we need this table to keep record of the qty of product in a particular document
  has_many :documentedMaterials
  has_many :documents, :through => :documentedMaterials
  
  #we need this table to keep record of location hierarchy
  has_many :childmaterials, :class_name => "Material"
  belongs_to :parentmaterial, :foreign_key => "parentmaterial_id", :class_name => "Material"
  
  has_many :vendorMaterials
  has_many :vendors, :through => :vendorMaterials
  
  has_and_belongs_to_many :materialGroups
end

app/models/package.rb
class Package < ActiveRecord::Base
  belongs_to :document
end

app/models/postick.rb
class Postick < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  #we need this table to keep record of the qty of product in a particular location
  has_many :locatedProducts
  has_many :locations, :through => :locatedProducts
  
  has_many :productmaterialdetails, :class_name => "ProductMaterialDetail"
  has_many :materials, :through => :productmaterialdetails
  
  has_many :documentedProducts
  has_many :documents, :through => :documentedProducts
  
  has_and_belongs_to_many :productGroups
end

app/models/product_group.rb
class ProductGroup < Group
  has_and_belongs_to_many :products
end

app/models/rma_order.rb
class RmaOrder < Document
  has_one :customer
end

app/models/rol.rb
class Rol < ActiveRecord::Base
  has_and_belongs_to_many :activities
  has_and_belongs_to_many :applicationUsers
end

app/models/schema.rb
class Schema < ActiveRecord::Base
  has_and_belongs_to_many :schemaFields
  has_and_belongs_to_many :fieldsGroups
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :addresses
  
  has_many :vendorMaterials
  has_many :materials, :through => :vendorMaterials
end

app/controllers/product_groups_controller.rb
class ProductGroupsController < ApplicationController
  # GET /product_groups
  # GET /product_groups.json
  def index
    @product_groups = ProductGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @product_groups }
    end
  end

  # GET /product_groups/1
  # GET /product_groups/1.json
  def show
    @product_group = ProductGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @product_group }
    end
  end

  # GET /product_groups/new
  # GET /product_groups/new.json
  def new
    @product_group = ProductGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @product_group }
    end
  end

  # GET /product_groups/1/edit
  def edit
    @product_group = ProductGroup.find(params[:id])
  end

  # POST /product_groups
  # POST /product_groups.json
  def create
    @product_group = ProductGroup.new(params[:product_group])

    respond_to do |format|
      if @product_group.save
        format.html { redirect_to @product_group, :notice => 'Product group was successfully created.' }
        format.json { render :json => @product_group, :status => :created, :location => @product_group }
      else
        format.html { render :action => "new" }
        format.json { render :json => @product_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /product_groups/1
  # PUT /product_groups/1.json
  def update
    @product_group = ProductGroup.find(params[:id])

    respond_to do |format|
      if @product_group.update_attributes(params[:product_group])
        format.html { redirect_to @product_group, :notice => 'Product group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @product_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /product_groups/1
  # DELETE /product_groups/1.json
  def destroy
    @product_group = ProductGroup.find(params[:id])
    @product_group.destroy

    respond_to do |format|
      format.html { redirect_to product_groups_url }
      format.json { head :ok }
    end
  end
end

app/helpers/product_groups_helper.rb
module ProductGroupsHelper
end

app/views/product_groups/_form.html.erb
<%= form_for(@product_group) do |f| %>
  <% if @product_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_group.errors.count, "error") %> prohibited this product_group from being saved:</h2>

      <ul>
      <% @product_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_groups/edit.html.erb
<h1>Editing product_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_group %> |
<%= link_to 'Back', product_groups_path %>

app/views/product_groups/index.html.erb
<h1>Listing product_groups</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @product_groups.each do |product_group| %>
  <tr>
    <td><%= product_group.id %></td>
    <td><%= product_group.name %></td>
    <td><%= product_group.description %></td>
    <td><%= link_to 'Show', product_group %></td>
    <td><%= link_to 'Edit', edit_product_group_path(product_group) %></td>
    <td><%= link_to 'Destroy', product_group, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product group', new_product_group_path %>

app/views/product_groups/new.html.erb
<h1>New product_group</h1>

<%= render 'form' %>

<%= link_to 'Back', product_groups_path %>

app/views/product_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @product_group.id %>
</p>

<p>
  <b>Name:</b>
  <%= @product_group.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product_group.description %>
</p>


<%= link_to 'Edit', edit_product_group_path(@product_group) %> |
<%= link_to 'Back', product_groups_path %>